wietlabs/krk_meetings

src/alternative_solvers/BfsConnectionSolver.py
src/alternative_solvers/BfsConnectionSolver_demo.py
src/alternative_solvers/BfsSolverData.py
src/alternative_solvers/BfsSolverExtractor.py

Handle weekdays in BfsSolver

---

src/alternative_solvers/BfsConnectionSolver.py

Use modulo by WEEK instead of DAY in BfsConnectionSolver

---

src/data_provider/Merger.py
src/data_provider/Parser.py

Handle exception days in GTFS Static Parser and Merger fix

---

requirements.txt
src/meetings/app.py
src/meetings/test_app.py

Add meetings API

---

backend/src/run.py

Rename setup.py to run.py

---

backend/src/data_managers/ConnectionDataManager.py

Fix typo in ConnectionDataManager

---

backend/src/rabbitmq/RmqConsumer.py
backend/src/rabbitmq/RmqHelper.py
backend/src/rabbitmq/RmqProducer.py

Lost stream connection issue resolved

---

backend/src/data_classes/Connection.py
backend/src/data_classes/Transfer.py
backend/src/data_classes/Walk.py
backend/src/data_classes/tests/test_Connection.py
backend/src/solver/ConnectionSolver.py
frontend/api/ConnectionsApi.js
frontend/screens/connections/details/actions/ActionsList.js
frontend/screens/connections/details/map/Map.js
frontend/screens/connections/plot/ConnectionResultsPlotScreen.js
frontend/screens/connections/results/ConnectionResult.js
frontend/screens/connections/results/ConnectionResults.js

Fix IndexErrors in Connection class bug + refactoring

---

backend/src/examples/flask_examples/example_connection.py
backend/src/examples/flask_examples/sample_queries.py
backend/src/solver/ConnectionSolver.py

The issue was bad end stop name in the query.

Check on bad end stop name fixed.

---

frontend/App.js
frontend/LinkManager.js
frontend/app.json
frontend/screens/accounts/ScanAccountQRCodeScreen.js
frontend/screens/accounts/ShowAccountQRCodeScreen.js
frontend/screens/connections/find/FindConnectionsScreen.js
frontend/screens/meetings/CreateMeetingScreen.js
frontend/screens/meetings/JoinMeetingScreen.js
frontend/screens/meetings/MeetingDetailsScreen.js
frontend/screens/meetings/MeetingsScreen.js
frontend/stacks/MeetingsStack.js
frontend/utils.js

Use deep linking for joining meetings

---

frontend/screens/connections/plot/ConnectionResultsPlot.js

Fix connection results plot bug for empty list

---

frontend/screens/connections/find/FindConnectionsScreen.js

Allow only future dates in date picker

---

frontend/screens/meetings/JoinMeetingScreen.js
frontend/screens/meetings/MeetingDetailsScreen.js

Display nickname if available in meeting details screen

---

frontend/utils.js

Use exactly 4 random digits in guest nickname

---

backend/src/examples/flask_examples/example_connection.py
backend/src/examples/flask_examples/loop_connection_query.py
backend/src/examples/flask_examples/sample_queries.py
backend/src/rabbitmq/RmqHelper.py
backend/src/solver/ConnectionSolver.py

Value error resolved

---

backend/src/config.py
backend/src/examples/flask_examples/example_connection.py
backend/src/examples/flask_examples/loop_connection_query.py
backend/src/examples/flask_examples/sample_queries.py
backend/src/rabbitmq/RmqConsumer.py
backend/src/rabbitmq/RmqHelper.py
backend/src/rabbitmq/RmqProducer.py
backend/src/solver/ConnectionSolver.py
backend/src/solver/ConnectionSolverConfiguration.py

Rabbitmq fixed

---

frontend/screens/meetings/SelectEndStopScreen.js

Improve responsiveness of select meeting spot screen

---

frontend/screens/connections/find/FindConnectionsScreen.js
frontend/screens/meetings/details/MeetingDetailsScreen.js

Show find connections button in meeting details

---

frontend/screens/accounts/AccountsScreen.js
frontend/screens/meetings/join/JoinMeetingScreen.js
frontend/utils.js

Generate random nickname when creating identity

---

frontend/screens/meetings/SelectEndStopScreen.js

Don't resize map only to locations on metric change

---

frontend/App.js
frontend/screens/timetable/TimetableScreen.js
frontend/stacks/TimetableStack.js

Change timetable URL

---

frontend/screens/timetable/TimetableScreen.js

Allow only specific URLs in timetable webview

---

frontend/screens/meetings/SelectEndStopScreen.js

Pre-select best suggested meeting point

---

frontend/screens/meetings/details/MeetingDetailsScreen.js

Improve meeting details screen

---

backend/src/server/MeetingsServer.py
backend/src/server/tests/test_app.py
frontend/api/MeetingsApi.js
frontend/screens/meetings/MeetingsScreen.js
frontend/screens/meetings/create/CreateMeetingScreen.js
frontend/screens/meetings/details/MeetingDetailsScreen.js

Allow members to leave meeting

---

backend/requirements.txt
backend/src/data_provider/gtfs_realtime/VehiclePositionsParser.py

Add GTFS Realtime VehiclePositions.pb parser

---

frontend/screens/connections/details/map/Map.js
frontend/screens/meetings/SelectEndStopScreen.js

Fix vertical padding in connection view map

---

frontend/screens/connections/details/map/Map.js
frontend/screens/connections/plot/ConnectionResultsPlot.js
frontend/screens/connections/results/ConnectionResultItem.js
frontend/screens/connections/results/WalkChip.js

Show walking paths in connection details map

---

frontend/screens/meetings/join/JoinMeetingScreen.js

Handle 404 Meeting not found response in join meeting screen

---

frontend/components/NearestStopsMap.js

Show only 6 nearest stops

---

frontend/components/DelayText.js
frontend/screens/connections/details/actions/TransferAction.js
frontend/screens/connections/find/FindConnectionsScreen.js
frontend/screens/connections/plot/ConnectionResultsPlot.js
frontend/screens/connections/results/ConnectionResultItem.js
frontend/utils.js

Show delays, refactor datetime handling functions

---

frontend/components/Loading.js
frontend/screens/meetings/MeetingsScreen.js
frontend/screens/meetings/details/MeetingDetailsScreen.js

Convert loading indicator into a separate component

---

backend/src/server/MeetingsServer.py
backend/src/server/tests/test_app.py
frontend/api/MeetingsApi.js
frontend/screens/meetings/details/MeetingDetailsScreen.js
frontend/utils.js

Allow meeting owner to pick meeting time

---

frontend/api/MeetingsApi.js
frontend/screens/meetings/MeetingsScreen.js
frontend/screens/meetings/SelectEndStopScreen.js
frontend/screens/meetings/SelectStartStopScreen.js
frontend/screens/meetings/details/MeetingDetailsScreen.js

Improve meetings API functions

---

frontend/screens/connections/results/ConnectionResultItem.js
frontend/utils.js

Fix time.toISOString-related error for walking-only connections

---

backend/requirements.txt
backend/src/scripts/plot.py

Add plotting scripts

---

backend/requirements.txt
backend/src/server/MeetingsServer.py

Add rate-limiting constraints to meetings API queries

---

backend/src/server/BackendServer.py

Limits added to backend server

---

backend/src/data_provider/DataProvider.py

Closes #346 
Co-Authored-By: Mikołaj Tomalik <58105407+tomalikem@users.noreply.github.com>

Fix DataProvider when config.json does not exist

---

frontend/screens/connections/plot/ConnectionResultsPlot.js
frontend/screens/connections/results/ConnectionResultItem.js
frontend/utils.js

Fix wrong times for walking-only connection in mobile app

---

frontend/screens/accounts/AccountsScreen.js

Show only loading indicator while fetching identities list

---

frontend/components/SelectAccount.js
frontend/screens/meetings/create/CreateMeetingScreen.js
frontend/screens/meetings/join/JoinMeetingScreen.js

Allow user to select identity when creating new meeting

---

backend/src/meetings/routes.py

Fix "UNIQUE constraint failed" error when joining a meeting

---

frontend/components/SelectAccount.js

Fix radio buttons not working when selecting identity

---

frontend/api/MeetingsApi.js
frontend/screens/meetings/details/MeetingDetailsScreen.js

Allow meeting owner to delete meeting

---

frontend/screens/meetings/join/JoinMeetingScreen.js

Fix duplicated meeting list screen after joining a meeting

---

backend/krk_meetings/data_provider/DataProvider.py
backend/krk_meetings/data_provider/DelaysProvider.py

TimeoutError resolved

---

backend/krk_meetings/scripts/pipeline_gtfs_realtime.py
backend/krk_meetings/scripts/pipeline_gtfs_static.py

GTFS Static & Realtime pipelines cleanup

---

backend/krk_meetings/performance_evaluation/calculate.py
backend/requirements-dev.txt

Calculate R^2 for meeting solver time vs participants count

---

frontend/screens/accounts/AccountsScreen.js
frontend/screens/meetings/MeetingsScreen.js

Fix add account icon in FAB group

---

frontend/components/StopsInputList.js

Don't show keyboard on find sequence screen focus

---

backend/krk_meetings/data_provider/DelaysExtractor.py
backend/krk_meetings/data_provider/gtfs_static/Parser.py

Fix KeyError when calendar_dates.txt is not found

---

meetings/utils.py

Fix TypeError when creating meeting using unnamed identity
